#if !canImport(ObjectiveC)
import XCTest

extension BSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BSONTests = [
        ("testBSONCorpus", testBSONCorpus),
        ("testDocument", testDocument),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BSONTests.__allTests__BSONTests),
    ]
}
#endif
